# General
seed: 42

# Paths
path_to_dataset: ../../datasets/calcium_imaging
path_to_results: ../../output

# Overwriting parameters
overwrite_mode: 'changes_only' # 'always', 'never', 'changes_only' for when params changed

# Analysis parameters
sampling_frequency: 30 # frames per second
z_threshold: 2 # Used to detect periods of putative activity
remove_inactivity: False # If true and data is binarized, will remove epochs where no cell was active

# Locomotor info
speed_threshold: 5 # cm.s-1
remove_immobility: False

# seqLT params
tone_threshold: .2

# Data curation thresholds
distance_travelled_threshold: 1000 # cm
occupancy_frame_threshold: 10 # min number of frames per location
portion_surface_covered_threshold: .8 # 0-1, default=1 (all bins explored)
input_neurons: 128 # Number of neurons to be used. Also minimum number required

# Tuning curve computations
temporalBinSize: .25 # s
distanceBinSize: 4 # cm
spatialBinSize: 4 # cm
directionBinSize: 9 # º
velocityBinSize: 4 # cm.s-1

max_distance_length: 100
max_temporal_length: 10
max_velocity_length: 30

# Tuning curve analysis
#rate_map_smoothing_sigma: 2 # cm, sigma for gaussian smoothing, 0 for no smoothing
rate_map_smoothing_size: 5 # cm, size for gaussian smoothing, 0 for no smoothing

# Chance analysis
num_surrogates: 1000 # Number of circular permutations

# Chronic alignment
max_centroid_dist: 5 # maximum distance between cell centroids in µm
min_spatial_corr: .65 # minimum spatial footprint correlation

# Embeddings
embedding_dims: 2
train_set_selection: random # 'random', random frames. 'split', split recording using train_test_ratio
train_test_ratio: .8 # portion of recording used to train embedding model

# UMAP-specific settings
min_dist: .8 # high values encourage smooth latents, low values encourage clustering
n_neighbors: 30

# Plotting
max_ca_traces_to_plot: 50
plot_gain: 3
portion_to_plot: 0.2 # Only plot the first portion of the recording