# General
device: cpu # Preferred device to training. Supported: 'cuda' (nvidia), 'mps' (apple metal shaders). If not available, will revert back to cpu
seed: 42

# Paths
path_to_dataset: ../../datasets/calcium_imaging
path_to_results: /results

# Experiment
overwrite_data: True # If file is present, re-analyse?

# Analysis parameters
sampling_frequency: 30 # frames per second
z_threshold: 2 # Used to detect periods of putative activity
remove_inactivity: False # If true and data is binarized, will remove epochs where no cell was active

# Locomotor info
speed_threshold: 5 # cm.s-1
remove_immobility: False

# seqLT params
tone_threshold: .2

# Data curation thresholds
distance_travelled_threshold: 3000 #cm
occupancy_frame_threshold: 20 # min number of frames per location
portion_surface_covered_threshold: .8 # 0-1, default=1 (all bins explored)
split_half_threshold: .3 # threshold for stability. Default = .3
min_num_neurons: 128 # Minimum number of neurons for a session to be included

# Tuning curve computations
temporalBinSize: 1
spatialBinSize: 2.5
max_cum_spatial_length: 536
max_cum_temporal_length: 10
#rate_map_smoothing_sigma: 2 # cm, sigma for gaussian smoothing, 0 for no smoothing
rate_map_smoothing_size: 5 # cm, size for gaussian smoothing, 0 for no smoothing

num_surrogates: 1000 # Number of circular permutations

# Chronic alignment parameters

# Embeddings
input_neurons: 128
embedding_dims: 2
train_set_selection: random # 'random', random frames. 'split', split recording using train_test_ratio
train_test_ratio: .8 # portion of recording used to train embedding model

# UMAP-specific settings
min_dist: .8
n_neighbors: 30

# Plotting
max_ca_traces_to_plot: 50
plot_gain: 3
portion_to_plot: 0.2 # Only plot the first portion of the recording